### PR TITLE
Updates selectors and added new ones

### PR DESCRIPTION
**Pull request by UsmanAhmadSaeed**
#33 
Updated selectors for profile pictures and added new selectors of profile pictures and names that were missing previously such as status view screen, group chat messages, message replies, voice messages.
I've tested locally on firefox by loading via about:debugging

### CODE REVIEW

**Comment by UsmanAhmadSaeed** [comment]
uh oh, sorry about that. I'll make a PR again.

**Comment by LukasLen** [comment]
Thanks for modifying the CSS files, I will look into this shortly and finish up the fix.

**Comment by UsmanAhmadSaeed** [comment]
Hey, Can you please restore the **LukasLen:v2.12.1** branch? I'd like to create a fork, since I had deleted my fork after merge, to update based on latest WhatsApp version. Thanks!

**Comment by LukasLen** [comment]
Hi! I just released a fix in a new version with 1ce7ae370633422263ae0ab033b8bc4ccd54c223

**Pull request merged**
