### PR TITLE
Add an option to adjust blur amount for each blur toggles

### LINKED ISSUE #12: Add an option to adjust blur amount
**Is your feature request related to a problem? Please describe.**
I would like to be able to blur certain elements but to a certain amount so that they're partially visible. 

**Describe the solution you'd like**
An option to adjust blur amount (e.g. using a percentage).

**Describe alternatives you've considered**
I was manually doing this using the Styler extension and just came about this extension. Here's the CSS I used:

```
._1Wn_k {
    color: transparent;
    text-shadow: 0 0 4px rgba(0,0,0,0.5);
}


._1Wn_k > span > img {
	filter: blur(4px)
}```

### PR DESCRIPTION
**Pull request by aryomuzakki**
Add new Feature to adjust blur amount, as requested in issue #12 

Tested on :
WhatsApp: v2.3000.1012850706
OS: Windows 10 22H2 64Bit Build 19045.4170
Browser: Brave Browser v1.64.122 with Chromium v123.0.6312.122 and Firefox v125.0.1

#### Example:
Default:
image
> Button will open or close the extra option. Options can only be closed by clicking option toggle again

Custom Blur Amount:
image
> Click Submit Button after changing value, to apply changes. 
> Reset button will reset value to default, then you still need to Submit to apply changes.

### CODE REVIEW

**Review by Tgentil — APPROVED** [review]
I would recommend updating the _locales files

**Review by LukasLen — APPROVED** [review]
Awesome stuff! I can do the German translation. Maybe someone can help out with translation for other languages later?

**Comment by Tgentil** [comment]
I can do the Brazilian portuguese translation

**Comment by LukasLen** [comment]
Perfect thank you, I will merge this now and we can work on this branch for v3.3.0.

**Pull request merged**
