### PR TITLE
fixes for latest whatsapp release

### PR DESCRIPTION
**Pull request by aritrakrbasu**

### CODE REVIEW

**Comment by Tgentil** [comment]
I've tested this PR and found it resolves the cache issue, which is great as it eliminates the need for constant cache clearing and relogging into WhatsApp Web. However, there are areas for improvement:

1. The 'Media Gallery' button isn't blurring.
2. The 'Group/Usernames' blur functionality seems inactive, but it appears to be linked to the 'Last Preview Media' button.
3. Adding comments next to new selectors would maintain code consistency and clarify the purpose of each selector.

For instance, in the section where new selectors are added without comments:

src/css/mediaPreview.css
```css
x1vjfegm /* New Selector Description */
```

Only the new selectors lacks a comments.

Despite these areas for improvement, I plan to continue using this version in Chrome's developer mode due to its effective solution to the caching issue.

**Comment by aritrakrbasu** [comment]
@Tgentil Thank you for your suggestion, I will update the codebase and will update this PR.

Thank you for the support ❤️

**Comment by Ahmed-Soli** [comment]
> @Tgentil Thank you for your suggestion, I will update the codebase and will update this PR.
> 
> Thank you for the support ❤️

Thanks for your efforts.

**Comment by aritrakrbasu** [comment]
Support for all button actions are updated !

**Comment by UsmanAhmadSaeed** [comment]
@aritrakrbasu Can I use your base to publish my own unlisted version on firefox for personal use?
And could you also share why the original extension had stopped working today? I haven't had a look at the differences/edits in your fix and previous.

**Comment by aritrakrbasu** [comment]
@UsmanAhmadSaeed you can go ahead and use my branch as it is under MIT license. The extension stopped working because WhatsApp has released a new build and due to that the CSS names has changes on their end as they are using module CSS the class names are generated using hash.

**Comment by LivreAcessoPro** [comment]
There is a version for Firefox ESR, @Tgentil

**Comment by Tgentil** [comment]
> There is a version for Firefox ESR, @Tgentil

@LivreAcessoPro  I haven't tested it on Firefox, but PR [#66](https://github.com/LukasLen/Privacy-Extension-For-WhatsApp-Web/pull/66) made by @aryomuzakki  appears robust and could be worth trying out on Firefox ESR. It resolved major issues in Chrome effectively, so it's possible it might work well on Firefox too.

**Comment by LivreAcessoPro** [comment]
@Tgentil 
image
Version 3.x does not support Firefox ESR.

**Comment by LukasLen** [comment]
Thanks for contributing! I will move forward with #66.

**Pull request closed without merging**
